[package]
name = "korman-screeps-bot"
version = "0.0.1"
description = "Guo Hao Rust Screeps AI bot"
repository = "https://github.com/korman/korman_screeps.git"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.70"
log = "0.4.22"
fern = "0.6.2"
screeps-game-api = { version = "0.23.1", features = ["mmo"] }
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--signext-lowering"]

[features]
default = []
sim = ["screeps-game-api/sim"]
mmo = ["screeps-game-api/mmo"]